# Generated by Django 2.2.3 on 2019-07-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_topic_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
    ]
